nft-qos: Correct device remove nft command.
Currently a pair of errors is generated whenever a device is removed
from the tracking tables:

Error: syntax error, unexpected handle
delete handle 7
Error: syntax error, unexpected handle
delete handle 8

Update remove operation to specify the table and chain so that it succeeds.